### PR TITLE
EOS-13994: Extend cortxfs_req.py for motr API start and end time attributes

### PR DESCRIPTION
**Pull request by vimalraghwani20**
Problem Statement
EOS-13994: Extend cortxfs_req.py for motr API start and end time attributes

Problem Description
We have introduced the start time and end time performance counter attributes to trace the amount of time required to execute moter API,
we need to handle these attributes in the python script to generate the appropriate attribute call graph with the start and end time. 

Solution Overview
Modified the script and added sequence of start and end time attributes as graph node after init state of any function tag and before finish state of any function tag.

Unit Test Cases
- UT
- cthon
- Call graph 
read_op_559193_1_call_attr
fsal_read_histogram
fsal_write_histogram
write_op_533682_1_call_attr

### CODE REVIEW

**Review by AtitaShirwaikar — APPROVED** [review]
+1

**Review by pratyush-seagate — APPROVED** [review]
LGTM, +1
Can you pls change all the existing "us" in this script to "ns"? The times are in ns, not in us.

**Comment by vimalraghwani20** [comment]
> LGTM, +1
> Can you pls change all the existing "us" in this script to "ns"? The times are in ns, not in us.

@pratyush-seagate  I have already address this change in PR. Can you please point it out if I missed anywhere that will be really helpful.

**Comment by pratyush-seagate** [comment]
> 
> 
> > LGTM, +1
> > Can you pls change all the existing "us" in this script to "ns"? The times are in ns, not in us.
> 
> @pratyush-seagate I have already addressed this change in PR.
> Can you please point it out if I missed anywhere, that will be really helpful.

I can confirm after checking all the time units are now correct.

**Review by sachinpunadikar — APPROVED** [review]
+1

**Pull request merged**
