### PR TITLE
EOS-13233 NFS job is failing for cortx-1.0 branch

### PR DESCRIPTION
**Pull request by SwapnilGaonkar7**
In this pull request we are adding support for space in path in which our code is present. Currently config/build is failing in path contains space in it (e.g /root/with space/temp/...).
To fix above issue I have encapsulated path uses with quotes, in some cases splited commands in 2 parts etc.

UT : refer to Seagate/cortx-posix#281

### CODE REVIEW

**Comment by s-arya** [comment]
@SwapnilGaonkar7 : Codacy checks have failed. Could you please check if these are valid checks?

**Review by s-arya — CHANGES_REQUESTED** [review]
Could you please check if the codacy checks that have failed are valid checks.

**Comment by SwapnilGaonkar7** [comment]
> Could you please check if the codacy checks that have failed are valid checks.

I have updated PRs to fix codacy check issues.

**Review by sachinpunadikar — APPROVED** [review]
+1

**Review by s-arya — APPROVED** [review]
LGTM. +1

**Review by Shreya-18 — APPROVED** [review]
Looks good +1

**Pull request merged**
