### PR TITLE
EOS-13985:Implement nfs_req.py and hist.py <cortxfs repo>

### PR DESCRIPTION
**Pull request by pratyush-seagate**
# EOS-13985:Implement nfs_req.py and hist.py <cortxfs repo>

## Checklist
- [x] **Compilation:** _This patch does not break compilation_
- [x] **Merge conflicts:** _This patch has been squashed and re-based, it can be merged using fast-forward merge_
- [] **Code review:** _All discussions have been resolved_
- [x] **Sanity Testing:** _All Unit tests are passing and able to do mount and io operations works from NFS client_
- [x] **Documentation:** _This patch and merge request have up to date description_
- [x] **Unit Testing and debugging:** _Both single and multi node changes are unit tested_

## Commit Message
        commit b93363c1eb1dbe08baf44ec412307d2b347ad2c6
        Author: pratyush-seagate <pratyush.k.khan@seagate.com>
        Date:   Mon Oct 12 17:05:15 2020 -0600

        EOS-13985:Implement nfs_req.py and hist.py <Part 1, cortxfs repo>
        List of modified files:
                modified:   src/tools/addb/scripts/addb2db_cortxfs.py
                new file:   src/tools/addb/scripts/cortxfs_req.py
                new file:   src/tools/addb/scripts/cortxfs_hist.py
        Change description:
                1. Add a python script named cortxfs_hist.py to generate histogram graphs with respect to operation and time from the perfor
                2. Add a python script named cortxfs_req.py to generate performance call graph based on the o/p generated by addb2db_cortxfs
                3. Update addb2db_cortxfs.py to track the operation id of immediate callers in map performance counters
        Unit test:
                Run NFS READ IO test, generate DB from addb2db_cortxfs.py, use that DB to find the fsal read op id which took most time to c
        TODO: Implement timeline tools
        The generate graph image along with DB file and raw dump files are saved at: /home/751521/JIRA/EOS-13985
                # python3 src/tools/addb/scripts/cortxfs_hist.py -d cortxfs_perfc_demo_decoded_1.db -o read_hist.svg fsal_read
                Creating cortxfs histogram graph for fn_tag fsal_read, from db file cortxfs_perfc_demo_decoded_1.db, o/p graph file read_his
                incomplete states, discarding this sample, [{'id': 4734, 'pid': 35, 'time': 1602494228965013040, 'tsdb_mod': 'fsuser_state',
    incomplete states, discarding this sample, [{'id': 5036, 'pid': 35, 'time': 1602494229051873985, 'tsdb_mod': 'fsuser_state', 'fn_tag': '
                Histogram graph render completed for operation fsal_read
                # python3 src/tools/addb/scripts/cortxfs_req.py -d ./cortxfs_perfc_demo_decoded_1.db 0x5C3F -o read_op_23615
                Creating cortxfs performance call graphs for fsal_op_id 23615, from db file ./cortxfs_perfc_demo_decoded_1.db, o/p graph png
                Graph render completed

### CODE REVIEW

**Comment by pratyush-seagate** [comment]
graph

**Review by vimalraghwani20 — APPROVED** [review]
Looks good to me

**Review by vimalraghwani20 — COMMENTED** [review]
Codacy check is failing.

**Review by AtitaShirwaikar — APPROVED** [review]

**Comment by pratyush-seagate** [comment]
> 
> 
> Codacy check is failing.

All the codacy warnings are now resolved except one,  "gen_perfc_op_call_graph is too complex (18) (MC0001)".

@AtitaShirwaikar  @sachinpunadikar  Please share your take on this. IMO, we can ignore this one, it looks like this function needs to be split into sub functions to make codacy happy.

**Review by shahidSTX — APPROVED** [review]
LGTM.

**Review by sachinpunadikar — APPROVED** [review]
+1

**Pull request merged**
